export const REQUEST_USER_LOCATION = 'REQUEST_USER_LOCATION';
export const RECEIVE_USER_LOCATION = 'RECEIVE_USER_LOCATION';
export const RECEIVE_USER_LOCATION_ERROR = 'RECEIVE_USER_LOCATION_ERROR';

export const MOVE_MAP_MARKER = 'MOVE_MAP_MARKER';
export const SET_FORM_VALUE = 'SET_FORM_VALUE';
